import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // As defined in design-system.md and globals.css
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway", // As defined in design-system.md and globals.css
  weight: ["400", "500", "600", "700"], // Weights specified in brand-guide.md
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={`${inter.variable} ${raleway.variable} font-sans antialiased`} suppressHydrationWarning data-testim-main-word-scripts-loaded="true">
        {children}
      </body>
    </html>
  );
}
